### ISSUE TITLE
make_mapped_structure fails for structures created with Structure.from_poscar

### ISSUE THREAD

**Issue by xivh** [prisms-center/CASMcode_mapping#11]
`make_mapped_structure` raises an error if the structure has molecule properties. However, structures created with  `Structure.from_poscar` have both atom and molecule properties, so in order to use these structures one has to convert the structure to a dictionary, delete the `mol_coords` and `mol_type` entries, and then convert back into a Structure.

https://github.com/prisms-center/CASMcode_mapping/blob/01fcf30ec0a53165480c4f7117a2d90b55864a0a/src/casm/mapping/StructureMapping.cc#L65

**Comment by bpuchala** [comment]
I'm going to change the `Structure.from_poscar` and `Structure.from_poscar_str` behavior to only set atom info for the Structure. This does seem better because the POSCAR does not contain any information to decide what is a Molecule vs Atom and also addresses this issue. 

One thing to note additionally is that the conversion to/from dict is not necessary. A new Structure can be constructed passing constructor arguments using the methods that access attributes of the existing Structure.
